import { afterEach, describe, expect, it, vi } from 'vitest';
import { createServer } from 'node:http';
import { once } from 'node:events';
import { createIntegrationHandler } from './api';
import { input } from './contracts.fixture';
import { createFixture } from '../../scripts/create-firm-fixture';
const servers:ReturnType<typeof createServer>[]=[];
afterEach(async()=>{for(const s of servers.splice(0)){s.closeAllConnections();await new Promise<void>(r=>s.close(()=>r()));}});
async function start(extra:Record<string,unknown>={}){const env={DOMINO_INTEGRATION_KEY:'token1',DOMINO_UI_ORIGINS:'http://127.0.0.1:5175',MISTRAL_API_KEY:'key1'};const handler=createIntegrationHandler({env,...extra});const s=createServer((req,res)=>void handler(req,res));servers.push(s);s.listen(0,'127.0.0.1');await once(s,'listening');return `http://127.0.0.1:${(s.address() as {port:number}).port}`;}
const headers={Authorization:'Bearer token1','Content-Type':'application/json'};
async function post(url:string,path:string,data:unknown){return fetch(url+'/api/v1'+path,{method:'POST',headers,body:JSON.stringify(data)});}
describe('versioned firm API actual HTTP',()=>{
 it('roundtrips a real SQLite matter through the actual engine and anchored memo',async()=>{const path=new URL('../../.verification/api-firm.sqlite',import.meta.url).pathname;await createFixture(path);const url=await start({env:{DOMINO_INTEGRATION_KEY:'token1',DOMINO_SQLITE_FILE:path,DOMINO_SQLITE_MATTERS:'demo-c1-c2'}});const imported=await post(url,'/matters/demo-c1-c2/import',{});expect(imported.status).toBe(201);expect((await imported.json()).bundle.docs).toHaveLength(9);const result=await (await post(url,'/cases/demo-c1-c2/analyse',{mode:'deterministic'})).json();expect(result.analysis.chains.map((c:{id:string})=>c.id)).toEqual(['C1','C2']);expect(Object.values(result.state.decisions)).toEqual(Array(5).fill('proposed'));expect(result.memoMarkdown).toContain('Invoice');expect(await (await fetch(url+'/api/v1/cases/demo-c1-c2/export',{headers})).json()).toEqual(result);});
 it('bounds provider timeout and local request rate without leaking diagnostics',async()=>{const fetcher=vi.fn((_url:unknown,options?:RequestInit)=>new Promise<Response>((_,reject)=>options?.signal?.addEventListener('abort',()=>reject(Error('private key1')))));const url=await start({fetcher,timeoutMs:5});const response=await post(url,'/providers/mistral/test',{});expect(response.status).toBe(502);expect(await response.text()).not.toContain('key1');const limited=await start({rateLimit:1});expect((await fetch(limited+'/api/v1/connections',{headers})).status).toBe(200);expect((await fetch(limited+'/api/v1/connections',{headers})).status).toBe(429);});
 it('fails closed without auth and when server token is unset',async()=>{const url=await start();expect((await fetch(url+'/api/v1/connections')).status).toBe(401);expect((await fetch(url+'/api/v1/connections',{headers:{Authorization:'Bearer bad'}})).status).toBe(401);const closed=await start({env:{}});expect((await fetch(closed+'/api/v1/connections',{headers})).status).toBe(503);});
 it('denies foreign origins and unauthenticated UI bridge',async()=>{const url=await start();expect((await fetch(url+'/api/v1/connections',{headers:{...headers,Origin:'https://evil.example'}})).status).toBe(403);expect((await fetch(url+'/api/connections/connections')).status).toBe(403);});
 it('imports, analyses and exports existing deterministic engine/memo with proposed decisions',async()=>{const url=await start();expect((await post(url,'/cases',input())).status).toBe(201);expect((await fetch(url+'/api/v1/cases/firm-1/export',{headers})).status).toBe(409);const analysed=await post(url,'/cases/firm-1/analyse',{mode:'deterministic'});expect(analysed.status).toBe(200);const result=await analysed.json();expect(result.state.decisions).toEqual({'qual-1':'proposed'});expect(result.memoMarkdown).toContain('Defence memo');const exported=await fetch(url+'/api/v1/cases/firm-1/export',{headers});expect(await exported.json()).toEqual(result);expect((await post(url,'/cases',input())).status).toBe(409);});
 it('rejects malformed JSON, content types, paths, oversized body and unsupported methods',async()=>{const url=await start();expect((await fetch(url+'/api/v1/cases',{method:'POST',headers,body:'null'})).status).toBe(400);expect((await fetch(url+'/api/v1/cases',{method:'POST',headers,body:'{'})).status).toBe(400);expect((await fetch(url+'/api/v1/cases',{method:'POST',headers:{Authorization:'Bearer token1'},body:'text'})).status).toBe(415);expect((await fetch(url+'/api/v1/cases',{method:'POST',headers,body:'x'.repeat(1024*1024+1)})).status).toBe(413);expect((await fetch(url+'/api/v1/connections',{method:'DELETE',headers})).status).toBe(405);expect((await post(url,'/cases', {...input(),path:'/private'})).status).toBe(400);});
 it('uses selected actual provider adapter and labels AI review without changing imported evidence',async()=>{
  const transport=vi.fn(async(_url:unknown,opts?:RequestInit)=>{expect(JSON.parse(String(opts?.body)).model).toBe('firm-model');return Response.json({choices:[{message:{content:JSON.stringify({notes:[{text:'Fake contract review only',documentIds:['doc-1']}]})}}]});});
  const env={DOMINO_INTEGRATION_KEY:'token1',FIRM_KEY:'key1',DOMINO_AI_PROFILES:JSON.stringify([{id:'firm-ai',label:'Firm API',protocol:'openai-compatible-chat',model:'firm-model',baseUrl:'http://127.0.0.1:9911/v1',credentialEnv:'FIRM_KEY',trustedOrigins:['http://127.0.0.1:9911']}])};
  const url=await start({env,fetcher:transport});await post(url,'/cases',input());const r=await post(url,'/cases/firm-1/analyse',{mode:'ai-review',profileId:'firm-ai'});expect(r.status).toBe(200);const x=await r.json();expect(x.aiReview.profileId).toBe('firm-ai');expect(x.aiReview).toMatchObject({live:true,providerUsed:'openai-compatible-chat',requestCount:1});expect(x.aiReview.label).toContain('not legal confirmation');expect(x.state.decisions['qual-1']).toBe('proposed');expect(transport.mock.calls[0][0]).toBe('http://127.0.0.1:9911/v1/chat/completions');
 });
 it('redacts provider errors and preserves last successful export',async()=>{const fetcher=vi.fn(async()=>{throw Error('key1 private server path');});const url=await start({fetcher});await post(url,'/cases',input());const good=await (await post(url,'/cases/firm-1/analyse',{mode:'deterministic'})).json();const failed=await post(url,'/cases/firm-1/analyse',{mode:'ai-review',profileId:'mistral'});expect(failed.status).toBe(502);expect(await failed.text()).not.toContain('key1');expect(await (await fetch(url+'/api/v1/cases/firm-1/export',{headers})).json()).toEqual(good);});
 it('rejects ungrounded AI output and unknown profile before changes',async()=>{const fetcher=vi.fn(async()=>Response.json({choices:[{message:{content:'{"notes":[{"text":"Fake","documentIds":["foreign"]}]}'}}]}));const url=await start({fetcher});await post(url,'/cases',input());expect((await post(url,'/cases/firm-1/analyse',{mode:'ai-review',profileId:'missing'})).status).toBe(404);expect(fetcher).not.toHaveBeenCalled();expect((await post(url,'/cases/firm-1/analyse',{mode:'ai-review',profileId:'mistral'})).status).toBe(502);});
 it('passes complete accepted document text to AI review without silent truncation',async()=>{
  const matter=input();const marker='END_OF_FULL_ACCEPTED_DOCUMENT';
  matter.documents[0].text += ' '.repeat(26000)+marker;
  let seen='';
  const fetcher=vi.fn(async(_url:unknown,opts?:RequestInit)=>{
   seen=JSON.parse(String(opts?.body)).messages.find((m:{role:string})=>m.role==='user').content;
   return Response.json({choices:[{message:{content:JSON.stringify({notes:[{text:'Test-only review',documentIds:['doc-1']}]})}}]});
  });
  const url=await start({fetcher});expect((await post(url,'/cases',matter)).status).toBe(201);
  expect((await post(url,'/cases/firm-1/analyse',{mode:'ai-review',profileId:'mistral'})).status).toBe(200);
  expect(seen).toContain(marker);expect(seen.length).toBeGreaterThan(24000);
 });
 it('returns public metadata and bounded test connection only',async()=>{const fetcher=vi.fn(async()=>Response.json({choices:[{message:{content:'{"ok":true}'}}]}));const url=await start({fetcher});const status=await (await fetch(url+'/api/v1/connections',{headers})).text();expect(status).not.toContain('key1');expect(status).not.toContain('MISTRAL_API_KEY');expect(status).toContain('voxtral');expect((await post(url,'/providers/mistral/test',{})).status).toBe(200);expect(fetcher).toHaveBeenCalledTimes(1);});
});
