import { useEffect, useRef, useState } from 'react';
import type { CaseBundle } from '../data/bundle';
import type { CaseExport } from '../integrations/types';
import { useLocale } from '../i18n/useLocale';
import { copyText, dialogKey } from '../integrations/interaction';
type Status={source:{configured:boolean};profiles:{id:string;label:string;model:string;configured:boolean;protocol:string}[];cases:{id:string;title:string|{en:string;fr:string};analysed:boolean}[]};
const API='/api/connections';
export function Connections({onClose,onView}:{onClose:()=>void;onView:(bundle:CaseBundle)=>void}){
  const panel = useRef<HTMLElement>(null);
  useEffect(() => { const before = document.activeElement as HTMLElement | null; panel.current?.querySelector<HTMLButtonElement>('button')?.focus(); return () => before?.focus(); }, []);
  const {locale,t}=useLocale();const label=(en:string,fr:string)=>locale==='fr'?fr:en;
  const [status,setStatus]=useState<Status|null>(null);const [matters,setMatters]=useState<{id:string;title:string}[]>([]);const [matterId,setMatterId]=useState('demo-c1-c2');
  const [profileId,setProfileId]=useState('');const [bundle,setBundle]=useState<CaseBundle|null>(null);const [result,setResult]=useState<CaseExport|null>(null);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');const [failed,setFailed]=useState(false);
  const request=async(path:string,data?:unknown)=>{const response=await fetch(API+path,{...(data!==undefined?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{})});const value=await response.json();if(!response.ok)throw Error(value.error??'Request failed.');return value;};
  const refresh=async()=>{const next:Status=await request('/connections');setStatus(next);setProfileId(current=>current||next.profiles.find(p=>p.configured)?.id||next.profiles[0]?.id||'');if(next.source.configured){const source=await request('/matters');setMatters(source.matters);}};
  useEffect(()=>{let mounted=true;fetch(API+'/connections').then(async r=>{const next=await r.json();if(!r.ok)throw Error(next.error);if(!mounted)return;setStatus(next);setProfileId(next.profiles.find((p:Status['profiles'][number])=>p.configured)?.id??next.profiles[0]?.id??'');if(next.source.configured){const source=await request('/matters');if(mounted)setMatters(source.matters);}}).catch(()=>{if(mounted){setFailed(true);setNotice(locale === 'fr' ? 'Connexions indisponibles. Démarrez la démo locale.' : 'Connections unavailable. Start the local integration demo.');}});return()=>{mounted=false;};},[locale]);
  const act=async(action:()=>Promise<void>)=>{setBusy(true);setNotice('');setFailed(false);try{await action();}catch(error){setFailed(true);setNotice(error instanceof Error && error.message.startsWith('Clipboard') ? label('Clipboard permission required; use Export result instead.','Autorisation du presse-papiers requise ; utilisez Exporter le résultat.') : label('Request failed. Check server configuration, API access or duplicate matter ID; previous results are unchanged.','Échec de la requête. Vérifiez la configuration, l’accès API ou un identifiant déjà importé ; les résultats précédents sont conservés.'));}finally{setBusy(false);}};
  const selected=status?.profiles.find(p=>p.id===profileId);
  const importMatter=()=>act(async()=>{const next=await request(`/matters/${encodeURIComponent(matterId)}/import`,{});setBundle(next.bundle);setResult(null);await refresh();setNotice(label('Imported source evidence. All legal decisions remain proposed.','Sources importées. Toutes les décisions juridiques restent proposées.'));});
  const run=(mode:'deterministic'|'ai-review')=>act(async()=>{if(!bundle)return;const next=await request(`/cases/${bundle.id}/analyse`,{mode,...(mode==='ai-review'?{profileId}:{})});setResult(next);await refresh();setNotice(label('Analysis ready. Lawyer review required.','Analyse disponible. Validation par un avocat requise.'));});
  const exported=async()=>{if(!bundle)throw Error();return request(`/cases/${bundle.id}/export`);};
  return <div className="connections-backdrop"><section ref={panel} onKeyDown={event => dialogKey(event, onClose, busy)} className="connections-panel" role="dialog" aria-modal="true" aria-labelledby="connections-title">
    <header className="connections-header"><div><span className="connections-kicker">DOMINO / {label('LOCAL WORKSPACE','ESPACE LOCAL')}</span><h1 id="connections-title">{label('Connections','Connexions')}</h1></div><button className="btn" disabled={busy} onClick={onClose}>{label('Close','Fermer')}</button></header>
    <p className="connections-lead">{label('Your evidence. Your AI API. A traceable result returned to your system.','Vos sources. Votre API IA. Un résultat traçable renvoyé à votre système.')}</p>
    <p className="callout amber">{label('Local single-tenant demo · synthetic data only · no automatic write-back · legal review required.','Démo locale mono-cabinet · données synthétiques uniquement · aucun renvoi automatique · validation juridique requise.')}</p>
    <div className="connections-grid">
      <section className="connection-card"><span className="connections-kicker">01 / {label('EVIDENCE','SOURCES')}</span><h2>{label('Synthetic SQLite demo bridge','Passerelle SQLite synthétique')}</h2>
        <p>{label('Read-only, server-configured matter selector. Other databases connect through the normalized push API.','Lecture seule et sélection de dossiers configurée côté serveur. Les autres bases utilisent l’API d’import normalisée.')}</p>
        <p className="connection-status">{status?.source.configured?label('Configured · read-only','Configurée · lecture seule'):label('Not configured','Non configurée')}</p>
        <label>{label('Matter','Dossier')}<select aria-label={label('Matter','Dossier')} value={matterId} disabled={busy||!matters.length} onChange={e=>setMatterId(e.target.value)}>{matters.length?matters.map(m=><option key={m.id} value={m.id}>{m.title}</option>):<option value="demo-c1-c2">{label('Waiting for demo bridge','En attente de la passerelle')}</option>}</select></label>
        <button className="btn" disabled={busy||!matters.length||Boolean(status?.cases.some(c=>c.id===matterId))} onClick={importMatter}>{label('Import matter','Importer le dossier')}</button>
        {!!status?.cases.length&&<label>{label('Imported cases','Dossiers importés')}<select aria-label={label('Imported cases','Dossiers importés')} value={bundle?.id??''} disabled={busy} onChange={e=>{const id=e.target.value;if(id)void act(async()=>{const next=await request(`/cases/${id}`);const previous=status.cases.find(c=>c.id===id)?.analysed ? await request(`/cases/${id}/export`) : null;setBundle(next.bundle);setResult(previous);});}}><option value="">{label('Choose an imported case','Choisir un dossier importé')}</option>{status.cases.map(c=><option key={c.id} value={c.id}>{t(c.title)}</option>)}</select></label>}
      </section>
      <section className="connection-card"><span className="connections-kicker">02 / {label('TEXT MODEL','MODÈLE TEXTE')}</span><h2>{label('Text AI API','API IA texte')}</h2><p>{label('Select a server-owned API profile. Model, trusted host and credential reference stay on the server.','Choisissez un profil API du cabinet. Modèle, hôte autorisé et référence du secret restent côté serveur.')}</p>
        <label>{label('AI profile','Profil IA')}<select aria-label={label('AI profile','Profil IA')} value={profileId} disabled={busy||!status} onChange={e=>setProfileId(e.target.value)}>{status?.profiles.map(p=><option key={p.id} value={p.id}>{p.label} · {p.model}{p.configured?'':label(' · missing API key',' · clé API absente')}</option>)}</select></label>
        <button className="btn" disabled={busy||!selected?.configured} onClick={()=>void act(async()=>{const probe=await request(`/providers/${profileId}/test`,{});setNotice(label(`Live API connection verified: ${probe.model}.`,`Connexion API vérifiée en direct : ${probe.model}.`));})}>{label('Test AI connection','Tester la connexion IA')}</button>
        <p className="connection-footnote">{label('API-enabled access required. A consumer ChatGPT, Claude or Le Chat subscription is not an API credential.','Accès API requis. Un abonnement grand public ChatGPT, Claude ou Le Chat ne constitue pas une clé API.')}</p><p className="connection-footnote">{label('Voice transcription: Mistral Voxtral · separate, unchanged.','Transcription vocale : Mistral Voxtral · distincte et inchangée.')}</p>
      </section>
    </div>
    <section className="connection-card connection-result"><span className="connections-kicker">03 / {label('ANALYSE & RETURN','ANALYSER ET EXPORTER')}</span><h2>{bundle?t(bundle.profile.title):label('Import a matter to begin','Importez un dossier pour commencer')}</h2>
      {bundle&&<p>{label(`${bundle.docs.length} documents · ${bundle.facts.length} source-anchored annotations · ${bundle.qualifications.length} proposed qualifications`,`${bundle.docs.length} documents · ${bundle.facts.length} annotations sourcées · ${bundle.qualifications.length} qualifications proposées`)}</p>}
      <div className="connection-actions"><button className="btn" disabled={busy||!bundle} onClick={()=>void run('deterministic')}>{label('Run deterministic analysis','Analyser avec le moteur déterministe')}</button><button className="btn" disabled={busy||!bundle||!selected?.configured} onClick={()=>void run('ai-review')}>{label('Add live AI review','Ajouter une revue IA en direct')}</button><button className="btn" disabled={busy||!bundle} onClick={()=>bundle&&onView(bundle)}>{label('View imported case','Voir le dossier importé')}</button><button className="btn" disabled={busy||!result} onClick={()=>void act(async()=>{const value=await exported();const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${bundle!.id}-export.json`;a.click();URL.revokeObjectURL(url);setNotice(label('Export response downloaded. No external system was written.','Réponse exportée et téléchargée. Aucun système externe n’a été modifié.'));})}>{label('Export result','Exporter le résultat')}</button><button className="btn" disabled={busy||!result} onClick={()=>void act(async()=>{await copyText(JSON.stringify(await exported(),null,2), navigator.clipboard);setNotice(label('Export response copied.','Réponse exportée copiée.'));})}>{label('Copy export','Copier l’export')}</button></div>
      {result&&<><p className="connection-footnote">{label('Export contains the server baseline with proposed decisions; browser-only confirmations and what-if previews are not transmitted.','L’export contient la référence serveur avec décisions proposées ; les confirmations et hypothèses du navigateur ne sont pas transmises.')}</p><ul className="connection-chains">{result.analysis.chains.map(chain=><li key={chain.id}><strong>{chain.id} · {chain.title}</strong><span>{t(chain.status)}</span></li>)}</ul><details><summary>{label('Deterministic memo preview','Aperçu de la note déterministe')}</summary><p className="connection-memo">{result.memoMarkdown}</p></details></>}
      {result?.aiReview&&<section><h3>{label('AI commentary — not legal confirmation','Commentaire IA — sans confirmation juridique')}</h3><p>{result.aiReview.profileId} · {result.aiReview.model}</p><ul>{result.aiReview.notes.map((note,i)=><li key={i}>{note.text}<small> · {note.documentIds.join(', ')}</small></li>)}</ul></section>}
    </section>
    <p role={failed?'alert':'status'} className={`connection-notice ${failed?'error':''}`}>{busy?label('Working…','Traitement…'):notice}</p>
    <details className="connection-card"><summary>{label('Developer API','API développeur')}</summary><p>{label('Firm connectors submit normalized document text; bearer authentication is mandatory. Export returns JSON, never sends it to an arbitrary URL.','Les connecteurs transmettent le texte normalisé ; l’authentification Bearer est obligatoire. L’export renvoie du JSON, jamais vers une URL arbitraire.')}</p><code className="connection-code">{'curl http://127.0.0.1:5175/api/v1/connections -H "Authorization: Bearer $DOMINO_INTEGRATION_KEY"'}</code><p><a href="/api/connections/openapi" target="_blank" rel="noreferrer">OpenAPI 3.1</a> · <span>POST /api/v1/cases → POST /api/v1/cases/:id/analyse → GET /api/v1/cases/:id/export</span></p></details>
  </section></div>;
}
